### ISSUE TITLE
mkosi -i raises OSError with Format=directory when trying to copy /var/run/minissdpd.sock from cache

### ISSUE THREAD

**Issue by dsmcfarl** [systemd/mkosi#132]
To reproduce:

mkosi.default
```
[Distribution]
Distribution=debian
Release=stretch

[Output]
Format=directory

[Packages]
Packages=
```

mkosi.build
```
touch $DESTDIR/share/test
```
Checked out from master (40df6a3), ran:
```
mkosi -i
```
Traceback:
```
Traceback (most recent call last):
  File "./mkosi", line 2883, in <module>
    main()
  File "./mkosi", line 2879, in main
    build_stuff(args)
  File "./mkosi", line 2825, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=True)
  File "./mkosi", line 2680, in build_image
    cached = reuse_cache_tree(args, workspace.name, run_build_script, for_cache, cached)
  File "./mkosi", line 2644, in reuse_cache_tree
    enumerate_and_copy(fname, os.path.join(workspace, "root"))
  File "./mkosi", line 1270, in enumerate_and_copy
    enumerate_and_copy(source, dest, suffix + "/" + entry.name)
  File "./mkosi", line 1270, in enumerate_and_copy
    enumerate_and_copy(source, dest, suffix + "/" + entry.name)
  File "./mkosi", line 1277, in enumerate_and_copy
    shutil.copy(entry.path, dest_path, follow_symlinks=False)
  File "/usr/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 6] No such device or address: 'image.cache-pre-dev/var/run/minissdpd.sock'
```

Host os is debian sid.

**Comment by poettering** [comment]
Hmm, /var/run should be a symlink to /run, and that should be a tmpfs, and hence nothing we copy into the image... maybe we need wrap out debootstrap calls to set this up properly, if it doesn't do so on its own...

**Comment by dsmcfarl** [comment]
@poettering I did a little more experimenting. You are correct, debootstrap sets up /var/run as a symlink to /run (a symlink with an absolute path) so the call to enumerate_and_copy ends up trying to copy /run which is the /run tmpfs on the host not /run inside the os tree we are building. What would you consider "set up properly"? Make /var/run a symlink to ../run instead of /run (i.e., a relative link)?

**Comment by poettering** [comment]
@dsmcfarl uh, mkosi should copy symlinks as symlinks and not copy them... Are you saying it follows symlinks while copying?

**Comment by poettering** [comment]
yuck. that's a bug then and should be fixed.

**Comment by dsmcfarl** [comment]
@poettering looks like an if statement after line 1269 that skips the recursive call to enumerate_and_copy if the directory is a symlink would solve it.

**Comment by poettering** [comment]
if you have a fix, a PR would be very welcome!

**Comment by dsmcfarl** [comment]
@poettering Ok. The problem looks to be a little deeper than I first thought though. We also need to handle special files (it hangs on trying to copy /dev/full) and making sure the directory symlinks still get created. Also the image.cache-pre-* directories need to be added to the ignore_patterns in install_build_src otherwise it hangs (probably trying to copy /dev/full!). I'm guessing this particular branch of the code hasn't been tested much.  I'll submit a PR and see where it goes.
